# Generated by Django 4.0.6 on 2022-12-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_language_created_language_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
