# Generated by Django 4.0.6 on 2022-12-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_language_description_language_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
